### ISSUE TITLE
fast-check tips to detect race conditions

### ISSUE THREAD

**Issue by dubzzz** [TomerAberbach/limit-concur#1]
👋 Hello,

I just opened the issue in case it can be helpful for the project.

**fast-check** comes with a built-in arbitrary to ease detection of race conditions. You might be interested into relying on it in your tests too. See:
- https://github.com/dubzzz/fast-check/blob/main/documentation/Tips.md#detect-race-conditions
- https://codesandbox.io/s/github/dubzzz/fast-check/tree/main/example?hidenavigation=1&module=/005-race/autocomplete/main.spec.tsx&previewwindow=tests&file=/005-race/counter/main.spec.ts

Please feel free to close the issue. It was mostly to let you know about the feature.

**Comment by TomerAberbach** [comment]
Thank you for pointing that out! I'll probably add a test for that when I find the time, but will close the issue for now. Thanks again! :smile:
